language: cpp

compiler:
  - gcc
  - clang

env:
  - AUTOTOOLS=no BUILD=shared
  - AUTOTOOLS=no BUILD=static
  - AUTOTOOLS=yes BUILD=shared
  - AUTOTOOLS=yes BUILD=static

before_install:
  - gem install sass
  - git clone https://github.com/sass/libsass.git
  - cd libsass && git submodule init && git submodule update && cd ..
  - export SASS_LIBSASS_PATH=libsass

script:
  - ./script/ci-build-libsass

after_success:
  - ./bin/sassc -v
  - ldd ./bin/sassc
